# Generated by Django 3.0.3 on 2020-05-29 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, default='New', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Handicrafts'), ('SS', 'Sarees'), ('G', 'Grossery'), ('P', 'Daily Needs')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('Isclubmem', models.BooleanField(default=False)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('userphoto', models.ImageField(null=True, upload_to='images/')),
                ('phone_number', models.IntegerField(default=False)),
                ('refer', models.CharField(default=False, max_length=6)),
                ('usermoney', models.FloatField(default=0.0)),
                ('childern', models.IntegerField(default=0)),
                ('level', models.FloatField(default=0.0)),
                ('desig', models.CharField(choices=[('MD', 'ManagingDirector')], default=False, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
