# Generated by Django 2.2.10 on 2020-06-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(default=False, max_length=6)),
                ('usermoney', models.FloatField(default=0.0)),
                ('childern', models.IntegerField(default=0)),
                ('level', models.FloatField(default=1.0)),
                ('desig', models.CharField(choices=[('MD', 'ManagingDirector'), ('SD', 'SubordianteDirector'), ('BD', 'BronzeDirector'), ('SD', 'SilverDirector'), ('GD', 'GoldDirector'), ('B', 'Beginner')], default='B', max_length=20)),
                ('travelfund', models.FloatField(default=0.0)),
                ('teamincome', models.FloatField(default=0.0)),
                ('downlineincome', models.FloatField(default=0.0)),
                ('team', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('refered_preson', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
    ]
