# Generated by Django 3.0.3 on 2020-05-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200529_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='childern',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='desig',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='refer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='usermoney',
        ),
        migrations.CreateModel(
            name='Clubmember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(default=False, max_length=6)),
                ('usermoney', models.FloatField(default=0.0)),
                ('childern', models.IntegerField(default=0)),
                ('level', models.FloatField(default=0.0)),
                ('desig', models.CharField(choices=[('MD', 'ManagingDirector')], default=False, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
    ]
