# Generated by Django 2.2.10 on 2020-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200614_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoin',
            name='desig',
            field=models.CharField(choices=[('ManagingDirector', 'ManagingDirector'), ('SubordianteDirector', 'SubordianteDirector'), ('BronzeDirector', 'BronzeDirector'), ('SilverDirector', 'SilverDirector'), ('GoldDirector', 'GoldDirector'), ('Beginner', 'Beginner')], default='B', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='desig',
            field=models.CharField(choices=[('ManagingDirector', 'ManagingDirector'), ('SubordianteDirector', 'SubordianteDirector'), ('BronzeDirector', 'BronzeDirector'), ('SilverDirector', 'SilverDirector'), ('GoldDirector', 'GoldDirector'), ('Beginner', 'Beginner')], default='B', max_length=20),
        ),
    ]
