# Generated by Django 3.0.3 on 2020-05-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='desig',
            field=models.CharField(choices=[('MD', 'ManagingDirector'), ('SD', 'SubordianteDirector'), ('BD', 'BronzeDirector'), ('SD', 'SilverDirector'), ('GD', 'GoldDirector'), ('B', 'Beginner')], default='B', max_length=20),
        ),
    ]
