# Generated by Django 2.2.10 on 2020-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200614_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoin',
            name='Acno',
            field=models.FloatField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubjoin',
            name='Ifsc',
            field=models.FloatField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubjoin',
            name='paytm',
            field=models.FloatField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clubjoin',
            name='desig',
            field=models.CharField(choices=[('ManagingDirector', 'ManagingDirector'), ('SubordianteDirector', 'SubordianteDirector'), ('BronzeDirector', 'BronzeDirector'), ('SilverDirector', 'SilverDirector'), ('GoldDirector', 'GoldDirector'), ('Beginner', 'Beginner')], default='Beginner', max_length=20),
        ),
    ]
