# Generated by Django 3.0.3 on 2020-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200530_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paidmem',
            field=models.BooleanField(default=False),
        ),
    ]
