# Generated by Django 2.2.10 on 2020-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200615_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dis_per',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0.5),
        ),
    ]
