# Generated by Django 2.2.10 on 2020-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200616_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pincode',
            field=models.IntegerField(default=1),
        ),
    ]
