# Generated by Django 2.2.10 on 2020-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_clubjoin_referincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoin',
            name='orderincome',
            field=models.FloatField(default=0.0),
        ),
    ]
