# Generated by Django 2.2.10 on 2020-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200618_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.DeleteModel(
            name='Clubmember',
        ),
    ]
