# Generated by Django 2.2.10 on 2020-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200619_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantit',
            field=models.IntegerField(default=1),
        ),
    ]
