# Generated by Django 2.2.10 on 2020-06-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_orderitem_quantit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantit',
        ),
    ]
