# Generated by Django 2.2.10 on 2020-06-20 07:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200620_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes_choice', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=5, null=True), blank=True, default=list, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes_feild', to='core.Sizes_class'),
        ),
    ]
