# Generated by Django 2.2.10 on 2020-06-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200620_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='oisize',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
    ]
