# Generated by Django 2.2.10 on 2020-06-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200620_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
