# Generated by Django 2.2.10 on 2020-06-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200620_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size_field',
        ),
    ]
