# Generated by Django 2.2.10 on 2020-06-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_item_size_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Sizes_class'),
        ),
    ]
