# Generated by Django 2.2.10 on 2020-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
    ]
