# Generated by Django 2.2.10 on 2020-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200620_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='has_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
