# Generated by Django 2.2.10 on 2020-06-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200621_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selcsize',
        ),
        migrations.AddField(
            model_name='item',
            name='selcsize',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
    ]
