# Generated by Django 2.2.10 on 2020-06-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200622_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='selcsize',
            field=models.CharField(blank=True, default=False, max_length=25, null=True),
        ),
    ]
