# Generated by Django 2.2.10 on 2020-06-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='images',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
