# Generated by Django 2.2.10 on 2020-06-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_reviews_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
