# Generated by Django 2.2.10 on 2020-06-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='HKR', max_length=20),
        ),
    ]
