# Generated by Django 2.2.10 on 2020-06-25 14:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoin',
            name='bonusincome',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clubjoin',
            name='levelincome',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='clubjoin',
            name='positionincome',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sizes_class',
            name='sizes_choice',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5, null=True), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='Itemimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
    ]
