# Generated by Django 2.2.10 on 2020-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200625_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
