# Generated by Django 2.2.10 on 2020-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200625_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
    ]
