# Generated by Django 2.2.10 on 2020-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_team_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/adds/')),
                ('position', models.CharField(choices=[('T', 'TOP'), ('M', 'MIDDLE'), ('B', 'BOTTOM')], max_length=1)),
                ('typeoa', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
