# Generated by Django 2.2.10 on 2020-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_itemdealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default=False, max_length=25, null=True),
        ),
    ]
