# Generated by Django 2.2.10 on 2020-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200703_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myorder',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
