# Generated by Django 2.2.10 on 2020-07-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200704_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.AddField(
            model_name='item',
            name='pweight',
            field=models.FloatField(default=-1),
        ),
    ]
