# Generated by Django 2.2.10 on 2020-07-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200704_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Handicrafts'), ('SS', 'Sarees'), ('G', 'Groceries'), ('P', 'Daily Needs'), ('FW', 'FashionWear'), ('F', 'FootWear'), ('FU', 'Furniture'), ('MW', 'MensWear'), ('BC', 'BeautyCare'), ('E', 'Electronics'), ('MA', 'MensAccessories'), ('WA', 'WomensAccessories')], max_length=2),
        ),
    ]
