# Generated by Django 2.2.10 on 2020-07-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200705_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(choices=[('DOD', 'Deals of the Day'), ('NA', 'New Arrivals'), ('FO', 'FlashSale On'), ('BSP', 'BestSeller Products'), ('DS', 'Sunday Sale'), ('DOW', 'Deals of this Week'), ('MTTDP', 'More than 30% Off on discount price'), ('GDO', 'Great Discounts on')], max_length=30)),
                ('day', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
