# Generated by Django 2.2.10 on 2020-07-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_categories_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='caption',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
    ]
