# Generated by Django 2.2.10 on 2020-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_sales_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='row',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], default=False, max_length=30, null=True),
        ),
    ]
