# Generated by Django 2.2.10 on 2020-07-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_sales_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extrasales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=30)),
                ('day', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('caption', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('row', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], default=False, max_length=30, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
            options={
                'verbose_name_plural': 'XtraSales',
            },
        ),
    ]
