# Generated by Django 2.2.10 on 2020-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_extrasales'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
