# Generated by Django 2.2.10 on 2020-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_categories_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoin',
            name='desig',
            field=models.CharField(choices=[('ManagingCaption', 'ManagingCaption'), ('SubordianteCaption', 'SubordianteCaption'), ('BronzeCaption', 'BronzeCaption'), ('SilverCaption', 'SilverCaption'), ('GoldCaption', 'GoldCaption'), ('Beginner', 'Beginner')], default='Beginner', max_length=20),
        ),
    ]
