# Generated by Django 2.2.10 on 2020-07-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20200708_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'Handicrafts'), ('SS', 'Sarees'), ('G', 'Grocery'), ('P', 'Daily Needs'), ('FW', 'Fashion Wear'), ('F', 'Foot Wear'), ('FU', 'Furniture'), ('MW', 'MensWear'), ('BC', 'Beauty Care'), ('E', 'Electronics'), ('MA', 'Mens Accessories'), ('WA', 'Womens Accessories'), ('MP', 'Mobiles and Mobile accessories'), ('HA', 'Home Appliances'), ('S', 'Sports'), ('HC', 'Health Care'), ('KW', 'Kids Wear'), ('B', 'Books'), ('AA', 'Auto Accessories'), ('J', 'Jewellery')], max_length=2),
        ),
    ]
