# Generated by Django 2.2.10 on 2020-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_amt',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
