# Generated by Django 2.2.10 on 2020-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20200710_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='club_schargeinc',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
