# Generated by Django 2.2.10 on 2020-07-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_item_club_schargeinc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoin',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
