# Generated by Django 2.2.10 on 2020-07-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_clubjoin_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubjoin',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='mydelivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='myordered_date',
            field=models.DateField(),
        ),
    ]
