# Generated by Django 2.2.10 on 2020-07-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20200713_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('head', models.CharField(max_length=15)),
                ('des', models.CharField(max_length=100)),
                ('urlf', models.URLField()),
                ('color', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'indigo'), ('G', 'success'), ('B', 'blue')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='clubjoin',
            name='fund_transfred',
            field=models.BooleanField(default=False),
        ),
    ]
