# Generated by Django 2.2.10 on 2020-07-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20200715_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='images',
        ),
        migrations.CreateModel(
            name='ReviewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='reviewimages')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviewsimages', to='core.Reviews')),
            ],
        ),
    ]
