# Generated by Django 2.2.10 on 2020-07-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200716_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsimage',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
            preserve_default=False,
        ),
    ]
