# Generated by Django 2.2.10 on 2020-07-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.RenameField(
            model_name='clubjoin',
            old_name='fund_transfred',
            new_name='fund_transfered',
        ),
    ]
