# Generated by Django 2.2.10 on 2020-07-20 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20200717_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoin',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
