# Generated by Django 2.2.10 on 2020-10-26 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20200717_0502'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Multipleimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        )
    ]
