# Generated by Django 3.0.8 on 2020-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_clubjoin_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalEcommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('head', models.CharField(max_length=15)),
                ('des', models.CharField(max_length=100)),
                ('urlf', models.URLField()),
                ('color', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'indigo'), ('G', 'success'), ('B', 'blue')], max_length=1)),
                ('position', models.CharField(choices=[('T', 'TOP'), ('M', 'MIDDLE'), ('B', 'BOTTOM')], max_length=3)),
            ],
        ),
    ]
