# Generated by Django 2.2.10 on 2020-10-26 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20201026_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_images',
            field=models.ManyToManyField(related_name='multiple_images', to='core.Multipleimage'),
        )
    ]
