# Generated by Django 2.2.10 on 2020-10-26 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20201026_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalEcommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('head', models.CharField(max_length=15)),
                ('des', models.CharField(max_length=100)),
                ('urlf', models.URLField()),
                ('color', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'indigo'), ('G', 'success'), ('B', 'blue')], max_length=1)),
                ('position', models.CharField(choices=[('T', 'TOP'), ('M', 'MIDDLE'), ('B', 'BOTTOM')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemsearch',
            name='item',
        ),
        migrations.AddField(
            model_name='clubjoin',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='COD',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='keywords',
            field=models.ManyToManyField(to='core.Itemsearch'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('BN', 'Buy Now'), ('S', 'Save')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('P', 'Paytm'), ('C', 'Cash On Delivery')], default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_name',
            field=models.CharField(choices=[('DOD', 'Deals of the Navaratri day'), ('NA', 'New Arrivals'), ('FO', 'NavaratriSale On'), ('BSP', 'BestSeller Products'), ('DS', 'Sunday Sale'), ('DOW', 'Deals of this Navaratri week'), ('MTTDP', 'More than 30% Off on discount price'), ('GDO', 'Great Discounts on')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Itemimage',
        ),
    ]
