# Generated by Django 2.2.10 on 2020-10-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20201026_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='extra_pics',
        ),
        migrations.RemoveField(
            model_name='item',
            name='keyword',
        ),
        migrations.DeleteModel(
            name='Itemsearch',
        ),
        migrations.DeleteModel(
            name='Multipleimage',
        ),
    ]
