# Generated by Django 2.2.10 on 2020-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20201026_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_pics',
            name='name',
            field=models.CharField(default='Pic', max_length=30),
            preserve_default=False,
        ),
    ]
