# Generated by Django 2.2.10 on 2020-10-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_orderitem_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubjoin',
            name='prod_ref_inc',
            field=models.FloatField(default=0.0),
        ),
    ]
