# Generated by Django 2.2.10 on 2020-10-27 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0089_clubjoin_prod_ref_inc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clickables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=500)),
                ('buttons', models.ManyToManyField(related_name='Redirectors', to='core.Clickables')),
                ('users', models.ManyToManyField(related_name='Subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
