# Generated by Django 2.2.10 on 2020-10-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_clickables_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickables',
            options={'verbose_name_plural': 'Clickables'},
        ),
    ]
