# Generated by Django 2.2.10 on 2020-10-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20201027_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrderItem'),
        ),
    ]
