# Generated by Django 2.2.10 on 2020-11-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20201028_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagebackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='Productbackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_name',
            field=models.CharField(choices=[('DOD', 'Deals of the day'), ('NA', 'New Arrivals'), ('FO', 'Flashsale On'), ('BSP', 'BestSeller Products'), ('DS', 'Sunday Sale'), ('DOW', 'Deals of this week'), ('MTTDP', 'More than 30% Off on discount price'), ('GDO', 'Great Discounts on')], max_length=30),
        ),
    ]
