# Generated by Django 2.2.10 on 2020-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20201102_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbackground',
            name='color',
            field=models.CharField(default='#fdde6c', max_length=10),
        ),
    ]
