# Generated by Django 2.2.10 on 2020-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20201102_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrasales',
            name='day',
        ),
        migrations.RemoveField(
            model_name='extrasales',
            name='row',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='day',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='row',
        ),
        migrations.AddField(
            model_name='extrasales',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extrasales',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagebackground',
            name='font_color',
            field=models.CharField(default='#000', max_length=10),
        ),
        migrations.AddField(
            model_name='productbackground',
            name='category_font_color',
            field=models.CharField(default='#fff', max_length=10),
        ),
        migrations.AddField(
            model_name='productbackground',
            name='font_color',
            field=models.CharField(default='#fff', max_length=10),
        ),
        migrations.RemoveField(
            model_name='extrasales',
            name='item',
        ),
        migrations.AddField(
            model_name='extrasales',
            name='item',
            field=models.ManyToManyField(to='core.Item'),
        ),
        migrations.RemoveField(
            model_name='sales',
            name='item',
        ),
        migrations.AddField(
            model_name='sales',
            name='item',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
