# Generated by Django 2.2.10 on 2020-11-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20201102_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='position',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='text',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='typeoa',
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(null=True, upload_to='images/ads/'),
        ),
    ]
