# Generated by Django 2.2.10 on 2020-11-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_ads_urlf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mrp_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_inc_ship',
            field=models.FloatField(default=0),
        ),
    ]
