# Generated by Django 2.2.10 on 2020-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20201104_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pics',
            field=models.ManyToManyField(blank=True, to='core.Multiple_Pics'),
        ),
    ]
