# Generated by Django 2.2.10 on 2020-11-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20201104_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='status',
            field=models.CharField(choices=[('R', 'Refund'), ('S', 'Shipped'), ('P', 'Order Packed'), ('D', 'Out For Delivery'), ('O', 'Order Placed')], default='O', max_length=3),
        ),
    ]
