# Generated by Django 2.2.10 on 2020-11-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_auto_20201104_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebackground',
            name='page',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Category'), ('S', 'Sales')], default='O', max_length=3),
        ),
        migrations.AddField(
            model_name='productbackground',
            name='page',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Category'), ('S', 'Sales')], default='O', max_length=3),
        ),
    ]
