# Generated by Django 2.2.10 on 2020-11-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20201104_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebackground',
            name='page',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Category'), ('S', 'Sales')], default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='productbackground',
            name='page',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Category'), ('S', 'Sales')], default='H', max_length=3),
        ),
    ]
