# Generated by Django 2.2.10 on 2020-11-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20201105_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubjoin',
            name='refered_person',
        ),
    ]
