# Generated by Django 2.2.10 on 2020-11-07 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20201107_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
