# Generated by Django 2.2.10 on 2020-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20201107_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='display',
            field=models.CharField(choices=[('D', 'Display'), ('N', 'Hide')], default='D', max_length=3),
        ),
    ]
