# Generated by Django 2.2.10 on 2020-11-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_ads_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickables',
            name='name',
            field=models.CharField(default='bt1', max_length=50),
            preserve_default=False,
        ),
    ]
