# Generated by Django 2.2.10 on 2020-11-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_clickables_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('A', 'All'), ('S', 'Specific')], default='A', max_length=3),
            preserve_default=False,
        ),
    ]
