# Generated by Django 2.2.10 on 2020-11-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_name',
            field=models.CharField(choices=[('DOD', 'Deals of the day'), ('FO', 'Flashsale On'), ('DS', 'Sunday Sale'), ('DOW', 'Deals of this week'), ('GDO', 'Great Discounts on')], max_length=30),
        ),
    ]
