# Generated by Django 2.2.10 on 2020-12-09 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('tag', models.CharField(blank=True, default='New', max_length=10, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('club_discount_price', models.FloatField(blank=True, default=100000, null=True)),
                ('dis_per', models.FloatField(blank=True, default=-1, null=True)),
                ('category', models.CharField(choices=[('H', 'Handicrafts'), ('SS', 'Sarees'), ('G', 'Grocery'), ('P', 'Daily Needs'), ('FW', 'Fashion Wear'), ('F', 'Foot Wear'), ('FU', 'Furniture'), ('MW', 'MensWear'), ('BC', 'Beauty Care'), ('E', 'Electronics'), ('MA', 'Mens Accessories'), ('WA', 'Womens Accessories'), ('MP', 'Mobiles and Mobile accessories'), ('HA', 'Home Appliances'), ('S', 'Sports'), ('HC', 'Health Care'), ('KW', 'Kids Wear'), ('B', 'Books'), ('AA', 'Auto Accessories'), ('J', 'Jewellery')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'indigo'), ('G', 'success'), ('B', 'blue')], default='P', max_length=1)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('pweight', models.FloatField(default=-1)),
                ('pincode', models.IntegerField(default=123456)),
                ('has_size', models.BooleanField(blank=True, default=False, null=True)),
                ('size', models.CharField(default=False, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('COD', models.BooleanField(blank=True, default=False, null=True)),
                ('review', models.BooleanField(default=False)),
                ('item_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Item')),
                ('kys', models.ManyToManyField(blank=True, to='core.Keyword')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pis', models.ManyToManyField(blank=True, to='core.Multiple_Pics')),
            ],
        ),
    ]
