from django.urls import path
from . import views
from django.conf.urls import (handler400, handler403, handler404, handler500)
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    AddCouponView,
    initiate_payment,
    callback,
    RequestRefundView,
    club,
    travels,
    orderpayment,
    ordercallback,
    landing,
    simp,
    privacy,
    returnpolicy,
    about,
    temp,
    sitemap,
    robots,
    Myorders,
    refund,
    Profile,
    test,
    categories,
    sales,
    push,
    clubpayment,
    refreshprod,
    contact,
    faqs,
    orderplaced,
    buy_now,
    reviewform,
    search_sales,
    search_xtrasales,
    Xtrasales,
    search,
    withdraw,
    downliners,
    auto
)

app_name = 'core'

urlpatterns = [
    path('ecommerce/', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('orderplaced/', orderplaced, name='orderplaced'),
    path('club/', club.as_view(), name='club'),
    path('refer-club/<slug>/', club.as_view(), name='refer-club'),
    path('travels/', travels.as_view(), name='travels'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('refer-product/<int:referid>/<slug:slug>/', ItemDetailView.as_view(), name='refered_product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('buynow/<slug>/', buy_now, name='buynow'),
    path('review/<int:userid>/<slug:slug>/', reviewform, name='reviewform'),
    path('refer-add-to-cart/<int:referid>/<slug:slug>/', add_to_cart, name='refer-add-to-cart'),
    path('refer-buynow/<int:referid>/<slug:slug>/', buy_now, name='refer-buynow'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('pay/', initiate_payment, name='pay'),
    path('callback/', callback, name='callback'),
    path('orderpayment/', orderpayment, name='orderpayment'),
    path('ordercallback/', ordercallback, name='ordercallback'),
    path('clubpayment/', clubpayment, name='clubpayment'),
    path('', HomeView.as_view(), name='landing'),
    path('simp/', simp, name='simp'),
    path('privacy/', privacy, name='privacy'),
    path('returnpolicy/', returnpolicy, name='returnpolicy'),
    path('about/', about, name='about'),
    path('tests/', temp.as_view(), name='temp'),
    path('sitemap.xml/', sitemap, name='sitemap.xml'),
    path('robots.txt/', robots, name='robots.txt'),
    path('myorders/', Myorders.as_view(), name='myorders'),
    path('refund/<int:pk>/', refund, name='refund'),
    path('profile/', Profile.as_view(), name='Profile'),
    path('refreshpaid/', test, name='test'),
    path('refreshprod/', refreshprod, name='refreshprod'),
    path('categories/<slug>/', categories, name='categories'),
    path('sales/<slug>/', sales, name='sales'),
    path('special-sales/<slug>/', Xtrasales, name='Xtrasales'),
    path('contact/', contact, name='contact'),
    path('faqs/', faqs, name='faqs'),
    path('sale/<slug>/', search_sales, name='search_sales'),
    path('extrasale/<slug>/', search_xtrasales, name='search_xtrasales'),
    path('products/<slug>/', search, name='category_search'),
    path('products/', search, name='normal_search'),
    path('withdraw/', withdraw, name='withdraw'),
    path('downliners/', downliners, name='downliners'),
    path('auto/', auto, name='auto'),
]