from django.urls import path
from . import views
from .views import (
    ItemDetailView,
    grossery,
    CheckoutView,
    HomeView,
    handicrafts,
    sarees,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    AddCouponView,
    initiate_payment,
    callback,
    RequestRefundView,
    club,
    travels,
    orderpayment,
    ordercallback,
    landing,
    dailyneeds,
    fashionwear,
    footwear,
    menswear,
    beautycare,
    furniture,
    electronics,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('club/', club.as_view(), name='club'),
    path('travels/', travels.as_view(), name='travels'),
    path('grossery/', grossery.as_view(), name='grossery'),
    path('handicrafts/', handicrafts.as_view(), name='handicrafts'),
    path('sarees/', sarees.as_view(), name='sarees'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('pay/', initiate_payment, name='pay'),
    path('callback/', callback, name='callback'),
    path('orderpayment/', orderpayment, name='orderpayment'),
    path('ordercallback/', ordercallback, name='ordercallback'),
    path('landing/', landing, name='landing'),
    path('dailyneeds/', dailyneeds.as_view(), name='dailyneeds'),
    path('fashionwear/', fashionwear.as_view(), name='fashionwear'),
    path('footwear/', footwear.as_view(), name='footwear'),
    path('menswear/', menswear.as_view(), name='menswear'),
    path('beautycare/', beautycare.as_view(), name='beautycare'),
    path('furniture/', furniture.as_view(), name='furniture'),
    path('electronics/', electronics.as_view(), name='electronics'),
]
